[workspace]

members = [
#    "rsbt",
#    "rsbt-app",
#    "rsbt-bencode",
    "rsbt-bencode-nom",
    "rsbt-bencode-derive",
    "rsbt-types",
    # "rsbt-web-common",
    # "rsbt-web-wizard",
]

[profile.release]
lto = true
