[package]
name = "rsbt-app"
categories = []
description = """
rsbt description.
"""
keywords = []

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = ["rt_tokio_1"]
rt_tokio_1 = ["rsbt-rt/tokio_1"]

[dependencies]
log = { workspace = true }

thiserror = "1"

clap = { workspace = true }

futures = { workspace = true }

rsbt-types = { path = "../rsbt-types" }
rsbt-rt = { path = "../rsbt-rt" }