[package]
name = "rsbt-app"
version = "0.1.1"
authors = ["Alexander Korolev <alexander.korolev.germany@gmail.com>"]
edition = "2018"
categories = []
description = """
rsbt description.
"""
homepage = "https://github.com/rsbt/rsbt"
keywords = []
license = "Unlicense OR MIT"
readme = "README.md"
repository = "https://github.com/rsbt/rsbt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

log = "0.4"

dirs = "3"

sha-1 = "0.9"
percent-encoding = "2"

uuid = { version = "0.8", features = ["v4"] }
rand = "0.7"

http = "0.2"
http-body = "0.3"
bytes = "0.5"
hyper = "0.13"
futures = "0.3"
futures_codec = "0.4"
async-trait = "0.1"
pin-utils = "0.1"

tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["full"] }


serde = { version = "1.0", features = ["derive"] }
serde_with = "1.5"

byteorder = "1.3"

toml = "0.5"

env_logger = "0.8"

rsbt-bencode = { path = "../rsbt-bencode" }
rsbt-types = { path = "../rsbt-types" }