use rsbt_app::{AppError, Config};

pub fn run_wizard(config: Config) -> Result<(), AppError> {
    println!("===========================================");
    println!("  Welcome to rsbt - Rust BitTorrent!");
    println!("===========================================");
    println!();
    println!("It looks like this is your first time running rsbt.");
    println!("Let me help you set up the configuration.");
    println!();

    // Step 1: Download directory
    let default_download = config.download_dir();
    println!("Download directory: {}", default_download.display());
    println!("  (Press Enter to use default, or type a new path)");

    // For now, use default - can be enhanced with stdin input later
    let download_dir = read_line_or_default(&default_download.display().to_string());

    let download_path = if download_dir.is_empty() {
        default_download
    } else {
        std::path::PathBuf::from(download_dir)
    };

    println!();
    println!("Download directory set to: {}", download_path.display());
    println!();

    // Create directories
    config
        .ensure_dirs()
        .map_err(|e| AppError::Config(e.to_string()))?;

    // Create default torrents.toml
    let config_path = config.torrents_config();
    if !config_path.exists() {
        let default_config = format!(
            "# rsbt configuration\n\
             # This file is automatically generated\n\
             \n\
             [download]\n\
             directory = \"{}\"\n",
            download_path.display()
        );
        std::fs::write(&config_path, default_config)
            .map_err(|e| AppError::Config(e.to_string()))?;
        println!("Created configuration file: {}", config_path.display());
    }

    println!();
    println!("===========================================");
    println!("  Setup complete!");
    println!("===========================================");
    println!();
    println!("Your files will be saved to: {}", download_path.display());
    println!("Configuration saved to: {}", config_path.display());
    println!();

    Ok(())
}

fn read_line_or_default(default: &str) -> String {
    // Simple implementation - in production, would use a crate like rustyline
    // For now, just return default
    // TODO: Implement interactive input with readline
    default.to_string()
}
